public class Variaveis {
    public static void main(String[] args) {
        // Declaração com Atribuição
        String nome = "Samuel";
        int idade = 29;
        float altura = 1.92f;
        double peso = 83.5;
        boolean casado = true;

        // Declaração sem Atribuição
        String titulo;
        int paginas;
        boolean capaDura;

        titulo = "Meu Primeiro Livro de Contos";
        paginas = 25;
        capaDura = false;
    }
}